apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 2                # {{ .Values.replicaCount }} → 예: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: kopo21/board:latest  # {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent  # {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/boarddb   # {{ .Values.mysql.port }} / {{ .Values.mysql.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: boarduser                        # {{ .Values.mysql.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: boardpass   