apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  type: ClusterIP          # {{ .Values.service.type }} → 예: ClusterIP / NodePort / LoadBalancer
  selector:
    app: springboot
  ports:
    - port: 80             # {{ .Values.service.port }} → 예: 80 (외부에서 접근할 포트)
      targetPort: 8080     # 컨테이너 내부 포트