name: Build and Push Docker, Update Manifest

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kopo21/board

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}   # 👈 TAG를 outputs로 노출
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag from short SHA
        id: vars
        run: echo "TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./board
          file: ./board/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifest branch
        uses: actions/checkout@v4
        with:
          ref: manifest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag in deployment.yaml
        run: |
          TAG=${{ needs.build-and-push.outputs.TAG }}
          sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${TAG}|g" k8s/deployment.yaml

      - name: Commit and push to manifest branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to $TAG" || echo "No changes to commit"
          git push origin manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}